---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
  - name: centos-5.10
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[lv::default]
    attributes:
